# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_DIR": "01_data.ipynb",
         "read_dataset": "01_data.ipynb",
         "add_time_feat": "01_data.ipynb",
         "split_train_test": "01_data.ipynb",
         "make_dataset": "01_data.ipynb",
         "DateSplitter": "01_data.ipynb",
         "create_dl": "01_data.ipynb",
         "get_dl": "01_data.ipynb",
         "get_emb_sz": "02_model.ipynb",
         "ConvPoolRecombine": "02_model.ipynb",
         "FGCNN": "02_model.ipynb",
         "train": "03_train.ipynb",
         "predict": "03_train.ipynb"}

modules = ["data.py",
           "model.py",
           "train.py"]

doc_url = "https://numb3r33.github.io/fgcnn/"

git_url = "https://github.com/numb3r33/fgcnn/tree/main/"

def custom_doc_links(name): return None
