# AUTOGENERATED! DO NOT EDIT! File to edit: 03_train.ipynb (unless otherwise specified).

__all__ = ['train', 'predict']

# Cell
from fastai.tabular.all import *
from fgcnn.data         import *
from fgcnn.model        import *

# Cell
def train(dls, m, lr, loss_func, n_epochs=1, opt_func=ranger, validate=False):
    learn = TabularLearner(dls, m, loss_func=loss_func, opt_func=ranger)
    learn.fit_flat_cos(n_epochs, lr, cbs=EarlyStoppingCallback())

    if validate:
        learn.validate()

    return learn

def predict(learner, df_test):
    dl             = learn.dls.test_dl(df_test)
    probs, y_preds = learn.get_preds(dl=dl)

    return probs